### ISSUE TITLE
Command line tool

### ISSUE THREAD

**Issue by Alex5719** [p0l0/pygruenbeck_cloud#56]
please provide a command line tool to read the state info of the Grünbeck device using this library and output the state info in the terminal in JSON.

this will help for fast integration into different home automation solutions

**Comment by Alex5719** [comment]
The command line tool could also act as an example on how to use the library

**Comment by p0l0** [comment]
The library is created for being used with the [Grünbeck Cloud Homeassistant Component](https://github.com/p0l0/hagruenbeck_cloud) and all responses are being converted into an Python Object, there will be no CLI implementation which outputs the returned data from API as JSON.

For an example using the library without Homeassistant, I posted an usage example in issue #52
